export type ControlTowerWisdom = {
  id: string
  author: string
  line: string
  application: string
  source: string
}

// Korean concise renderings of verified management quotations / core principles.
// They are intentionally not presented as literal translations. Source metadata is kept
// with every entry so future edits can preserve attribution accuracy.
export const CONTROL_TOWER_WISDOM: ControlTowerWisdom[] = [
  {
    id: 'drucker-01',
    author: '피터 드러커',
    line: '사업의 목적은 고객을 만들고 지키는 것이다.',
    application: '두배는 매출 숫자만 보지 않습니다. 다시 주문할 거래처를 만들고, 판매 이후 수금까지 끝나는 관계를 쌓아야 사업이 남습니다.',
    source: 'Peter F. Drucker — The Practice of Management / Drucker Institute',
  },
  {
    id: 'drucker-02',
    author: '피터 드러커',
    line: '올바른 일을 제대로 하는 것이 경영의 본질이다.',
    application: '두배는 바쁜 일보다 돈과 직결된 일을 먼저 봅니다. 오늘의 매출, 미수금, 현금, 생산 리스크 순서로 우선순위를 정합니다.',
    source: 'Peter F. Drucker — effectiveness principle / Drucker Institute',
  },
  {
    id: 'drucker-03',
    author: '피터 드러커',
    line: '계획은 실행으로 바뀌지 않으면 좋은 의도에 불과하다.',
    application: '두배의 계획은 반드시 다음 행동과 기한으로 바뀌어야 합니다. 목표매출도 방문·견적·재접촉·수금 일정이 없으면 계획으로 보지 않습니다.',
    source: 'Peter F. Drucker — Management: Tasks, Responsibilities, Practices',
  },
  {
    id: 'drucker-04',
    author: '피터 드러커',
    line: '리더십은 사람의 강점을 한 방향으로 모으는 일이다.',
    application: '두배는 한 사람이 모든 일을 잘하기를 기대하지 않습니다. 영업·생산·창고·관리의 역할을 분명히 하고 강점이 성과로 이어지게 배치합니다.',
    source: 'Peter F. Drucker — Management: Tasks, Responsibilities, Practices',
  },
  {
    id: 'drucker-05',
    author: '피터 드러커',
    line: '병목은 결국 병의 머리에서 시작된다.',
    application: '매출이 막히거나 생산이 늦을 때 현장만 탓하지 않습니다. 승인 지연, 우선순위 혼선, 잘못된 기준처럼 경영 판단의 병목부터 확인합니다.',
    source: 'Peter F. Drucker — Management',
  },
  {
    id: 'drucker-06',
    author: '피터 드러커',
    line: '다른 사람을 관리하기 전에 자신부터 관리하라.',
    application: '두배의 관리자는 먼저 자신의 일정·결정·보고 기한을 지켜야 합니다. 관리자의 지연은 아래 업무 전체의 지연으로 번집니다.',
    source: 'Peter F. Drucker — Managing Oneself',
  },
  {
    id: 'drucker-07',
    author: '피터 드러커',
    line: '책임을 맡긴다면 판단할 수 있는 권한도 함께 줘야 한다.',
    application: '두배는 담당자를 이름만 올려두지 않습니다. 책임 범위와 승인 기준을 함께 정해 담당자가 실제로 다음 행동을 결정할 수 있게 합니다.',
    source: 'Peter F. Drucker — responsibility and decentralization principles',
  },
  {
    id: 'drucker-08',
    author: '피터 드러커',
    line: '미래를 맞히려 하지 말고 이미 보이는 변화를 읽어라.',
    application: '두배는 막연한 전망보다 실제 주문, 미수금, 원재료 부족, 생산계획 변화를 먼저 봅니다. 이미 나타난 신호를 놓치지 않는 것이 경영입니다.',
    source: 'Peter F. Drucker — official Druckerism on visible change',
  },
  {
    id: 'drucker-09',
    author: '피터 드러커',
    line: '조직은 자신이 만든 영향까지 책임져야 한다.',
    application: '식품회사의 성과는 매출로 끝나지 않습니다. 위생, 품질, 소비기한, 기록 정확성까지 지켜야 두배의 매출이 오래갑니다.',
    source: 'Peter F. Drucker — Management: Tasks, Responsibilities, Practices',
  },
  {
    id: 'drucker-10',
    author: '피터 드러커',
    line: '혁신은 기업가정신을 실행하는 도구다.',
    application: '두배의 혁신은 새 기능을 많이 만드는 일이 아닙니다. 더 잘 팔고, 덜 버리고, 더 빨리 수금하고, 실수를 줄이는 변화가 실제 혁신입니다.',
    source: 'Peter F. Drucker — Innovation and Entrepreneurship',
  },
  {
    id: 'drucker-11',
    author: '피터 드러커',
    line: '궁극적인 경제 자원은 사람이다.',
    application: '설비와 프로그램이 있어도 사람이 기준을 이해하지 못하면 운영은 무너집니다. 두배는 교육과 역할 명확화를 비용이 아니라 생산성 투자로 봅니다.',
    source: 'Peter F. Drucker — official Druckerism on people as the ultimate resource',
  },
  {
    id: 'drucker-12',
    author: '피터 드러커',
    line: '노력보다 결과로 경영을 판단하라.',
    application: '영업 전화 수와 방문 수만으로 성과를 판단하지 않습니다. 실제 주문, 실제 수금, 재구매, 생산 손실 감소처럼 회사에 남은 결과를 봅니다.',
    source: 'Peter F. Drucker — effectiveness and accountability principles / Drucker Institute',
  },

  {
    id: 'deming-01',
    author: 'W. 에드워즈 데밍',
    line: '나쁜 시스템은 좋은 사람도 이긴다.',
    application: '같은 실수가 반복되면 개인을 먼저 탓하지 않습니다. 입력 방식, 승인 절차, 작업지시, 재고 흐름 중 어디가 실수를 만들었는지부터 고칩니다.',
    source: 'W. Edwards Deming — Four Day Deming Seminar, 1993 / Deming Institute',
  },
  {
    id: 'deming-02',
    author: 'W. 에드워즈 데밍',
    line: '시스템을 관리하려면 연결관계를 먼저 이해해야 한다.',
    application: '두배에서 판매·수금·현금·원재료·생산은 따로 움직이지 않습니다. 한 숫자의 변화가 다음 단계에 어떤 영향을 주는지 함께 봅니다.',
    source: 'W. Edwards Deming — The Essential Deming',
  },
  {
    id: 'deming-03',
    author: 'W. 에드워즈 데밍',
    line: '검사만으로 품질은 좋아지지 않는다.',
    application: '완제품 검사에서 불량을 잡는 것보다 레시피, 계량, 작업지시, LOT, 원재료 상태를 처음부터 정확히 관리하는 편이 더 싸고 안전합니다.',
    source: 'W. Edwards Deming — Out of the Crisis',
  },
  {
    id: 'deming-04',
    author: 'W. 에드워즈 데밍',
    line: '방법 없는 숫자 목표는 사람을 두렵게 만들 뿐이다.',
    application: '월 목표매출만 던져놓지 않습니다. 필요한 파이프라인, 다음 접촉일, 견적, 주문, 수금 단계까지 보여줘 목표를 실행 가능한 일로 만듭니다.',
    source: 'W. Edwards Deming — Out of the Crisis',
  },
  {
    id: 'deming-05',
    author: 'W. 에드워즈 데밍',
    line: '고객의 요구와 무관한 품질은 의미가 없다.',
    application: '두배가 좋다고 생각하는 제품보다 거래처가 안정적으로 쓰고 다시 주문하는 제품이 좋은 제품입니다. 품질 기준은 실제 사용과 재구매로 확인합니다.',
    source: 'W. Edwards Deming — Statistical Techniques and International Trade',
  },
  {
    id: 'deming-06',
    author: 'W. 에드워즈 데밍',
    line: '리더는 판사가 아니라 코치여야 한다.',
    application: '오류가 생기면 책임자를 찾는 것으로 끝내지 않습니다. 왜 틀렸는지 알려주고 SOP와 화면을 고쳐 다음에는 같은 오류가 나지 않게 합니다.',
    source: 'W. Edwards Deming — Western Connecticut State University, 1990 / Deming Institute',
  },
  {
    id: 'deming-07',
    author: 'W. 에드워즈 데밍',
    line: '사람도 시스템의 일부다.',
    application: '새 프로그램만 설치한다고 운영이 좋아지지 않습니다. 담당자 교육, 역할, 보고, 작업 보조수단까지 함께 설계해야 실제 성과가 바뀝니다.',
    source: 'W. Edwards Deming — Out of the Crisis',
  },
  {
    id: 'deming-08',
    author: 'W. 에드워즈 데밍',
    line: '현장 사람을 탓하기 전에 시스템부터 고쳐라.',
    application: '재고나 LOT가 계속 틀린다면 입력한 사람만 고치게 하지 않습니다. 자동생성 규칙과 검증 로직을 고쳐 같은 오류가 구조적으로 반복되지 않게 합니다.',
    source: 'W. Edwards Deming — Out of the Crisis / Deming Institute',
  },
  {
    id: 'deming-09',
    author: 'W. 에드워즈 데밍',
    line: '최선의 노력만으로는 부족하다. 무엇을 해야 하는지 알아야 한다.',
    application: '열심히 일했다는 사실보다 정확한 우선순위가 중요합니다. 오늘 받아야 할 돈, 부족 원재료, 지연 작업지시처럼 먼저 해야 할 일을 분명히 합니다.',
    source: 'W. Edwards Deming — knowledge before best efforts principle / Deming Institute',
  },
  {
    id: 'deming-10',
    author: 'W. 에드워즈 데밍',
    line: '데이터의 목적은 행동할 근거를 만드는 데 있다.',
    application: 'MONI는 숫자를 많이 보여주기 위해 존재하지 않습니다. 등록된 사실만 연결해 오늘 누구에게 연락하고 무엇을 생산하며 어디서 돈을 지킬지 결정하게 합니다.',
    source: 'W. Edwards Deming — Some Theory of Sampling / Deming Institute',
  },

  {
    id: 'juran-01',
    author: '조지프 주란',
    line: '품질은 사용하기에 적합해야 한다.',
    application: '규격에 맞았다는 이유만으로 충분하지 않습니다. 거래처가 실제 조리·판매 과정에서 안정적으로 쓸 수 있어야 두배의 품질로 인정합니다.',
    source: 'Joseph M. Juran — fitness for use / ASQ',
  },
  {
    id: 'juran-02',
    author: '조지프 주란',
    line: '결과를 좌우하는 중요한 소수에 집중하라.',
    application: '모든 문제를 동시에 잡지 않습니다. 큰 미수금 몇 건, 생산을 멈출 원재료 몇 종, 반복되는 주요 불량 원인부터 먼저 해결합니다.',
    source: 'Joseph M. Juran — Pareto principle / Juran Institute',
  },
  {
    id: 'juran-03',
    author: '조지프 주란',
    line: '품질은 계획하고, 관리하고, 개선해야 한다.',
    application: '두배의 품질은 검사표 한 장이 아닙니다. 생산 전 기준 설정, 생산 중 통제, 생산 후 원인 개선이 이어져야 다음 LOT가 더 좋아집니다.',
    source: 'Joseph M. Juran — Juran Trilogy',
  },
  {
    id: 'juran-04',
    author: '조지프 주란',
    line: '불량을 없애는 일은 비용을 줄이는 일이다.',
    application: '재작업·폐기·반품은 품질 문제이면서 현금 문제입니다. 생산 로스와 불량 원인을 금액으로 연결해 개선 우선순위를 정합니다.',
    source: 'Joseph M. Juran — quality deficiencies and cost / Juran Institute',
  },
  {
    id: 'juran-05',
    author: '조지프 주란',
    line: '품질은 최고경영진이 직접 책임져야 한다.',
    application: '품질을 생산직만의 책임으로 두지 않습니다. 경영자는 원재료 기준, 작업지시, 인력, 설비, 교육에 필요한 자원을 결정해야 합니다.',
    source: 'Joseph M. Juran — leadership involvement in quality / Juran Institute',
  },
  {
    id: 'juran-06',
    author: '조지프 주란',
    line: '품질의 최종 판단자는 고객이다.',
    application: '내부 검사 합격만 보지 않습니다. 클레임, 재주문, 반품, 거래처 사용 불편을 함께 기록해 실제 시장에서의 품질을 판단합니다.',
    source: 'Joseph M. Juran — customer-defined quality / Juran Institute',
  },
  {
    id: 'juran-07',
    author: '조지프 주란',
    line: '개선은 특정한 해가 아니라 매년 계속되어야 한다.',
    application: '문제가 사라진 것처럼 보여도 끝내지 않습니다. 월별 생산 로스, 재고 차이, 미수금 회수기간을 계속 비교해 작은 악화를 일찍 잡습니다.',
    source: 'Joseph M. Juran — continuous improvement / Juran Institute',
  },
  {
    id: 'juran-08',
    author: '조지프 주란',
    line: '좋은 품질은 검사보다 설계에서 시작된다.',
    application: '레시피, 공정, 포장단위, 원재료 규격을 애초에 명확히 설계하면 현장의 판단 부담과 재작업이 줄고 생산원가도 안정됩니다.',
    source: 'Joseph M. Juran — Quality Planning / Juran Trilogy',
  },

  {
    id: 'ohno-01',
    author: '오노 다이이치',
    line: '주문을 받은 순간부터 현금을 회수할 때까지의 시간을 줄여라.',
    application: '두배가 가장 중요하게 보는 흐름입니다. 견적→주문→출고→수금 사이의 대기시간을 줄여야 매출이 장부가 아니라 실제 현금이 됩니다.',
    source: 'Taiichi Ohno — Toyota Production System',
  },
  {
    id: 'ohno-02',
    author: '오노 다이이치',
    line: '필요한 것을, 필요한 때에, 필요한 만큼만 만든다.',
    application: '판매 가능성만 믿고 과잉생산하지 않습니다. 실제 주문과 생산계획을 연결해 원재료와 완제품에 현금이 과도하게 묶이지 않게 합니다.',
    source: 'Taiichi Ohno / Toyota Production System — Just-in-Time',
  },
  {
    id: 'ohno-03',
    author: '오노 다이이치',
    line: '과잉생산은 가장 먼저 경계해야 할 낭비다.',
    application: '팔리지 않은 재고는 매출이 아니라 묶인 현금입니다. 생산량을 늘리기 전에 판매속도와 재고일수를 함께 확인합니다.',
    source: 'Taiichi Ohno — Toyota Production System / TPS waste principle',
  },
  {
    id: 'ohno-04',
    author: '오노 다이이치',
    line: '정보도 필요한 순간에 필요한 만큼만 흘러야 한다.',
    application: 'MONI는 모든 데이터를 경고로 만들지 않습니다. 오늘 행동이 필요한 미수금, 자금 부족, 원재료 위험만 먼저 보여줘 판단 피로를 줄입니다.',
    source: 'Taiichi Ohno — Toyota Production System, information and JIT',
  },
  {
    id: 'ohno-05',
    author: '오노 다이이치',
    line: '표준이 없으면 개선도 없다.',
    application: 'LOT, 작업지시, 소비기한, 생산기록의 기준이 먼저 고정되어야 오류를 비교하고 개선할 수 있습니다. 사람마다 다른 방식은 개선의 기준이 될 수 없습니다.',
    source: 'Taiichi Ohno — standardized work principle associated with TPS',
  },
  {
    id: 'ohno-06',
    author: '오노 다이이치',
    line: '움직임이 많다고 일이 많이 된 것은 아니다.',
    application: '영업의 전화·방문 수가 많아도 주문과 수금이 없으면 성과가 아닙니다. 생산도 이동과 대기보다 실제 가치가 만들어진 시간을 봅니다.',
    source: 'Taiichi Ohno — work versus motion principle',
  },
  {
    id: 'ohno-07',
    author: '오노 다이이치',
    line: '다음 공정을 고객처럼 생각하라.',
    application: '창고는 생산이 쓰기 좋은 상태로 원재료를 넘기고, 생산은 출고가 바로 처리할 수 있게 기록을 끝냅니다. 내부 인계도 고객 납품처럼 정확해야 합니다.',
    source: 'Toyota Production System — supermarket / downstream customer principle',
  },
  {
    id: 'ohno-08',
    author: '오노 다이이치',
    line: '낭비를 줄이면 시간과 현금이 함께 돌아온다.',
    application: '대기, 중복입력, 불필요한 재고, 재작업을 줄이는 것은 단순한 효율화가 아닙니다. 두배가 같은 자금으로 더 많이 움직일 수 있게 하는 일입니다.',
    source: 'Taiichi Ohno — Toyota Production System / waste elimination',
  },

  {
    id: 'ishikawa-01',
    author: '이시카와 가오루',
    line: '품질관리는 교육에서 시작해 교육으로 끝난다.',
    application: '규칙을 문서로 만들어도 담당자가 이유와 방법을 모르면 지켜지지 않습니다. 새 기준은 교육하고 실제 기록으로 이해 여부를 확인합니다.',
    source: 'Kaoru Ishikawa — company-wide quality control philosophy',
  },
  {
    id: 'ishikawa-02',
    author: '이시카와 가오루',
    line: '품질은 전 직원이 참여할 때 강해진다.',
    application: '품질팀만 보는 문제가 아닙니다. 입고·창고·생산·출고·영업이 각 단계의 이상을 기록해야 불량이 고객까지 가기 전에 막을 수 있습니다.',
    source: 'Kaoru Ishikawa — company-wide quality control / ASQ',
  },
  {
    id: 'ishikawa-03',
    author: '이시카와 가오루',
    line: '고객 만족에서 품질을 시작하라.',
    application: '두배의 품질 기준은 내부 편의가 아니라 거래처가 원하는 맛, 규격, 납기, 일관성에서 출발합니다. 반복 주문이 최고의 품질 신호입니다.',
    source: 'Kaoru Ishikawa — customer satisfaction focus / ASQ',
  },
  {
    id: 'ishikawa-04',
    author: '이시카와 가오루',
    line: '대부분의 문제는 기본적인 데이터 도구로도 풀 수 있다.',
    application: '복잡한 AI보다 먼저 불량 유형, LOT, 날짜, 원재료, 생산량을 정확히 기록합니다. 원인이 보이면 해결책도 훨씬 단순해집니다.',
    source: 'Kaoru Ishikawa — basic QC tools / Quality Management Journal citation',
  },
  {
    id: 'ishikawa-05',
    author: '이시카와 가오루',
    line: '회사는 함께 일하는 사람의 삶을 존중해야 한다.',
    application: '두배는 사람을 소모품처럼 쓰지 않습니다. 명확한 기준과 안전한 작업환경을 만들고, 불필요한 혼선과 재작업을 줄이는 것도 경영의 책임입니다.',
    source: 'Kaoru Ishikawa — people and company responsibility philosophy',
  },
  {
    id: 'ishikawa-06',
    author: '이시카와 가오루',
    line: '문제를 탓하지 말고 원인을 구조로 그려보라.',
    application: '생산 오류가 나면 사람 이름으로 끝내지 않습니다. 원재료·방법·설비·환경·측정·작업조건으로 원인을 나눠 재발 원인을 찾습니다.',
    source: 'Kaoru Ishikawa — cause-and-effect analysis legacy / ASQ',
  },

  {
    id: 'taylor-01',
    author: '프레더릭 W. 테일러',
    line: '과거에는 사람이 먼저였지만, 미래에는 시스템이 먼저다.',
    application: '숙련자의 기억에만 의존하지 않습니다. 생산·재고·LOT·수금 기준을 시스템에 남겨 담당자가 바뀌어도 같은 방식으로 운영되게 합니다.',
    source: 'Frederick Winslow Taylor — The Principles of Scientific Management',
  },
  {
    id: 'taylor-02',
    author: '프레더릭 W. 테일러',
    line: '감에 의존하지 말고 일하는 방법을 검증하라.',
    application: '원가, 소모량, 생산시간, 재고 차이를 느낌으로 판단하지 않습니다. 실제 기록을 비교해 어떤 방법이 더 낫고 싼지 확인합니다.',
    source: 'Frederick Winslow Taylor — science, not rule of thumb',
  },
  {
    id: 'taylor-03',
    author: '프레더릭 W. 테일러',
    line: '불화보다 조화가 더 큰 생산성을 만든다.',
    application: '영업이 무리한 납기를 약속하고 생산이 뒤늦게 알게 되는 구조를 막습니다. 판매와 생산이 같은 일정과 숫자를 보게 해야 충돌 비용이 줄어듭니다.',
    source: 'Frederick Winslow Taylor — harmony, not discord',
  },
  {
    id: 'taylor-04',
    author: '프레더릭 W. 테일러',
    line: '개인주의보다 협력이 더 큰 결과를 만든다.',
    application: '각 부서가 자기 일만 끝냈다고 보지 않습니다. 주문이 수금되고 생산이 납기 안에 끝날 때까지 하나의 회사 흐름으로 책임을 연결합니다.',
    source: 'Frederick Winslow Taylor — cooperation, not individualism',
  },
  {
    id: 'taylor-05',
    author: '프레더릭 W. 테일러',
    line: '작업량보다 전체 산출을 높이는 방법을 찾아라.',
    application: '바쁜 시간을 늘리는 것이 목표가 아닙니다. 같은 인원과 시간으로 출고 가능한 제품과 회수되는 현금을 늘리는 방향으로 공정을 개선합니다.',
    source: 'Frederick Winslow Taylor — maximum output principle',
  },
  {
    id: 'taylor-06',
    author: '프레더릭 W. 테일러',
    line: '사람이 가장 잘 일할 수 있도록 방법과 역량을 함께 발전시켜라.',
    application: '성과가 부족하면 압박만 높이지 않습니다. 필요한 도구, SOP, 교육, 권한이 갖춰졌는지 확인하고 사람이 성과를 낼 조건부터 만듭니다.',
    source: 'Frederick Winslow Taylor — development of each worker principle',
  },

  {
    id: 'fayol-01',
    author: '앙리 파욜',
    line: '경영은 예측하고, 계획하고, 조직하고, 조정하고, 통제하는 일이다.',
    application: '두배의 Control Tower는 이 흐름을 숫자로 연결합니다. 목표를 세우고 자원을 배치한 뒤 실제 매출·수금·생산이 계획대로 가는지 확인합니다.',
    source: 'Henri Fayol — General and Industrial Management',
  },
  {
    id: 'fayol-02',
    author: '앙리 파욜',
    line: '통제란 계획대로 일이 진행되는지 확인하는 것이다.',
    application: '계획을 등록하는 것으로 끝내지 않습니다. 생산실적, 미수금, 현금흐름, 목표 달성률을 실제값과 비교해 차이가 생긴 즉시 조치합니다.',
    source: 'Henri Fayol — General and Industrial Management',
  },
  {
    id: 'fayol-03',
    author: '앙리 파욜',
    line: '통제의 목적은 실수를 찾고 다시 일어나지 않게 하는 것이다.',
    application: '잘못된 LOT나 재고가 발견되면 해당 숫자만 수정하지 않습니다. 생성 규칙과 입력 검증까지 고쳐 다음 생산에서는 같은 오류가 나오지 않게 합니다.',
    source: 'Henri Fayol — control principle',
  },
  {
    id: 'fayol-04',
    author: '앙리 파욜',
    line: '권한이 있는 곳에는 반드시 책임이 따라야 한다.',
    application: '승인권자가 결정을 미루면 그 지연도 책임으로 봅니다. 두배는 권한, 담당자, 기한을 함께 기록해 책임의 공백을 만들지 않습니다.',
    source: 'Henri Fayol — authority and responsibility principle',
  },
  {
    id: 'fayol-05',
    author: '앙리 파욜',
    line: '한 사람에게 서로 다른 두 명령을 주지 마라.',
    application: '생산 담당자가 여러 사람에게서 다른 지시를 받지 않게 합니다. 작업지시서 하나를 공식 기준으로 삼아 현장 혼선을 막습니다.',
    source: 'Henri Fayol — unity of command principle',
  },
  {
    id: 'fayol-06',
    author: '앙리 파욜',
    line: '하나의 목표에는 하나의 방향과 하나의 계획이 필요하다.',
    application: '매출을 늘리려는 영업계획과 현금을 지키려는 생산계획이 충돌하지 않게 합니다. 회사 전체가 같은 월 목표와 자금 기준을 보고 움직입니다.',
    source: 'Henri Fayol — unity of direction principle',
  },

  {
    id: 'follett-01',
    author: '메리 파커 폴렛',
    line: '사람 위의 힘보다 사람과 함께 만드는 힘이 강하다.',
    application: '지시만 내리는 조직보다 현장 정보가 위로 올라오는 조직이 강합니다. 두배는 생산·창고 담당자가 발견한 문제를 경영 판단에 바로 연결합니다.',
    source: 'Mary Parker Follett — power-with, not power-over',
  },
  {
    id: 'follett-02',
    author: '메리 파커 폴렛',
    line: '좋은 답은 타협보다 함께 새로 만드는 데서 나온다.',
    application: '영업과 생산이 서로 절반씩 포기하는 대신 납기·수량·재고 데이터를 함께 보고 고객과 회사 모두 지킬 수 있는 새 조건을 찾습니다.',
    source: 'Mary Parker Follett — integration / constructive conflict',
  },
  {
    id: 'follett-03',
    author: '메리 파커 폴렛',
    line: '갈등은 없애야 할 것이 아니라 제대로 다뤄야 할 차이다.',
    application: '부서 간 의견 차이를 감추지 않습니다. 매출, 원가, 생산능력처럼 서로 다른 근거를 한 화면에 놓고 더 나은 결정을 만드는 재료로 씁니다.',
    source: 'Mary Parker Follett — Constructive Conflict',
  },
  {
    id: 'follett-04',
    author: '메리 파커 폴렛',
    line: '사람의 명령보다 상황의 사실이 기준이 되어야 한다.',
    application: '직급이 높은 사람의 감보다 실제 재고, 수금일, 생산능력, 원가가 우선입니다. 두배의 결정은 가능한 한 등록된 사실에 복종합니다.',
    source: 'Mary Parker Follett — The Law of the Situation',
  },
  {
    id: 'follett-05',
    author: '메리 파커 폴렛',
    line: '좋은 리더는 다른 사람도 스스로 힘을 느끼게 한다.',
    application: '모든 결정을 대표에게 몰아두지 않습니다. 기준과 데이터가 명확한 일은 담당자가 책임 있게 결정하도록 해 조직의 속도를 높입니다.',
    source: 'Mary Parker Follett — leadership writings / Dynamic Administration',
  },

  {
    id: 'simon-01',
    author: '허버트 사이먼',
    line: '완벽한 답보다 제한된 현실에서 충분히 좋은 결정을 찾아라.',
    application: '모든 정보가 모일 때까지 기다리다 기회를 놓치지 않습니다. 다만 없는 숫자를 만들어내지 않고, 현재 확인된 정보 안에서 보수적으로 결정합니다.',
    source: 'Herbert A. Simon — bounded rationality / Administrative Behavior',
  },
  {
    id: 'simon-02',
    author: '허버트 사이먼',
    line: '경영의 중심에는 결국 의사결정이 있다.',
    application: 'MONI의 목적은 보고서를 많이 만드는 것이 아닙니다. 지금 돈을 받을지, 무엇을 생산할지, 어떤 위험을 먼저 막을지 결정하게 하는 것입니다.',
    source: 'Herbert A. Simon — decision-making in economic organizations / Nobel Prize',
  },
  {
    id: 'simon-03',
    author: '허버트 사이먼',
    line: '정보가 넘칠수록 가장 부족해지는 것은 주의력이다.',
    application: '대시보드에 모든 숫자를 같은 크기로 쌓지 않습니다. 오늘 회사의 현금과 납기에 영향을 주는 신호부터 위에 올려 경영자의 집중력을 지킵니다.',
    source: 'Herbert A. Simon — attention and information principle',
  },
  {
    id: 'simon-04',
    author: '허버트 사이먼',
    line: '복잡한 문제는 작은 결정 단위로 나눌수록 다룰 수 있다.',
    application: '큰 경영 문제를 한 번에 해결하려 하지 않습니다. 목표매출, 파이프라인, 수금, 자금, 생산 위험으로 나눠 각각 다음 행동을 정합니다.',
    source: 'Herbert A. Simon — organizational decision process',
  },

  {
    id: 'crosby-01',
    author: '필립 크로스비',
    line: '품질은 요구사항을 정확히 지키는 것이다.',
    application: '좋아 보인다는 감각보다 레시피, 중량, 포장, 소비기한, 납기처럼 합의된 요구사항을 정확히 지키는 것을 두배의 기본 품질로 봅니다.',
    source: 'Philip B. Crosby — conformance to requirements / ASQ',
  },
  {
    id: 'crosby-02',
    author: '필립 크로스비',
    line: '처음부터 바르게 하는 것이 가장 싸다.',
    application: '잘못 생산한 뒤 선별하고 재작업하는 비용보다 작업지시와 계량을 처음부터 정확히 하는 비용이 훨씬 작습니다.',
    source: 'Philip B. Crosby — do things right the first time / ASQ',
  },
  {
    id: 'crosby-03',
    author: '필립 크로스비',
    line: '불량을 당연한 수준으로 받아들이지 마라.',
    application: '작은 재고 차이와 기록 오류를 관행으로 넘기지 않습니다. 반복되는 작은 오차가 결국 원가, 납기, 고객 신뢰를 무너뜨립니다.',
    source: 'Philip B. Crosby — zero defects philosophy / ASQ',
  },
  {
    id: 'crosby-04',
    author: '필립 크로스비',
    line: '예방은 사후수정보다 값싸다.',
    application: '오류가 난 뒤 사람을 붙여 정리하기보다 입력 단계에서 검증하고, 작업 전 부족 원재료를 경고하고, 출고 전 수금조건을 확인합니다.',
    source: 'Philip B. Crosby — prevention culture / Quality Is Free',
  },
  {
    id: 'crosby-05',
    author: '필립 크로스비',
    line: '품질 비용은 품질을 만드는 비용이 아니라 잘못을 고치는 비용이다.',
    application: '품질관리에 돈이 든다고 줄이기보다 폐기·재작업·반품·긴급배송에 얼마가 새는지 먼저 봅니다. 실패비용을 줄이는 것이 이익을 지키는 길입니다.',
    source: 'Philip B. Crosby — Quality Is Free philosophy',
  },
  {
    id: 'crosby-06',
    author: '필립 크로스비',
    line: '품질은 별도 부서가 아니라 경영 방식이다.',
    application: '두배는 품질을 생산 현장에만 맡기지 않습니다. 구매, 재고, 생산, 영업, 고객 대응까지 같은 기준으로 연결해야 불량과 손실이 줄어듭니다.',
    source: 'Philip B. Crosby — quality management philosophy / ASQ',
  },
]

export const CONTROL_TOWER_WISDOM_COUNT = CONTROL_TOWER_WISDOM.length
