import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const page = readFileSync('src/app/mobile/page.tsx', 'utf8')
const polish = readFileSync('src/components/MoniMobileUxPolish.tsx', 'utf8')
const runtime = readFileSync('src/app/api/moni/agent-runtime/route.ts', 'utf8')
const userFacing = readFileSync('src/lib/moni/agent/user-facing-text.ts', 'utf8')
const pdfRoute = readFileSync('src/app/api/moni/answer-pdf/route.ts', 'utf8')
const statementPdf = readFileSync('src/app/api/moni/sales-statement-pdf/route.ts', 'utf8')
const statementResolver = readFileSync('src/lib/moni/documents/sales-statement-resolver.ts', 'utf8')
const pdfRenderer = readFileSync('src/lib/moni/documents/simple-pdf.ts', 'utf8')
const docxDocument = readFileSync('src/app/api/moni/answer-report/route.ts', 'utf8')
const toolBackend = readFileSync('src/lib/moni/agent/tool-backend.ts', 'utf8')
const conversationTools = readFileSync('src/lib/moni/agent/conversation-tools.ts', 'utf8')

test('mobile user question bubble is light and readable', () => {
  assert.match(page, /MoniMobileUxPolish/)
  assert.match(polish, /#def5ee/i)
  assert.match(polish, /#173b52/i)
  assert.match(polish, /#c7e8df/i)
  assert.match(polish, /answer-pdf/)
  assert.match(polish, /sales-statement-pdf/)
})

test('internal MONI labels and stale PDF instructions are removed before users see generated documents', () => {
  assert.match(userFacing, /unaccounted/)
  assert.match(userFacing, /계획-완료 차이/)
  assert.match(userFacing, /supplier_statement_balances/)
  assert.match(userFacing, /거래처 명세서 잔액/)
  assert.match(userFacing, /search_production_records/)
  assert.match(userFacing, /생산 기록 조회/)
  assert.match(runtime, /sanitizeMoniUserFacingText\(result\.text\)/)
  assert.match(runtime, /safeMessages/)
  assert.match(userFacing, /protectMarkdownDestinations/)
  assert.match(userFacing, /MONI_LINK_/)
  assert.match(userFacing, /PDF로\\s\*저장하는/)
  assert.match(userFacing, /stripGeneratedDocumentLinks/)
})

test('PDF requests return an authenticated real PDF download link with clean readable rendering', () => {
  assert.match(runtime, /isPdfDocumentRequest\(message\)/)
  assert.match(runtime, /removePdfCapabilityRefusal/)
  assert.match(runtime, /\/api\/moni\/answer-pdf\?thread_id=/)
  assert.match(runtime, /assistant_message_id/)
  assert.match(pdfRoute, /getSessionFromRequest/)
  assert.match(pdfRoute, /removePdfCapabilityRefusal/)
  assert.match(pdfRoute, /stripGeneratedDocumentLinks/)
  assert.match(pdfRoute, /MONI 분석 문서/)
  assert.match(pdfRoute, /application\/pdf/)
  assert.match(pdfRoute, /Content-Disposition/)
  assert.match(pdfRoute, /buildMoniReportPdf/)
  assert.match(pdfRenderer, /HYGoThic-Medium/)
  assert.match(pdfRenderer, /KSCms-UHC-H/)
  assert.match(pdfRenderer, /characterSpacing/)
  assert.match(pdfRenderer, /footer\(value: string\)/)
  assert.doesNotMatch(pdfRenderer, /bullet: '•'/)
})

test('sales statement requests resolve canonical MONI sales data and follow-up selection without guessing', () => {
  assert.match(runtime, /resolveSalesStatementArtifacts/)
  assert.match(runtime, /거래명세표 PDF 다운로드/)
  assert.match(runtime, /MONI 거래명세표 양식 열기/)
  assert.match(runtime, /거래명세표를 만들 거래를 특정해야 합니다/)
  assert.match(statementResolver, /DB-\\d\{8\}-\\d\{3\}/)
  assert.match(statementResolver, /sales_orders/)
  assert.match(statementResolver, /requestedOrdinal/)
  assert.match(statementResolver, /artifacts\.length === 1/)
  assert.match(statementResolver, /canonical_form_url/)
  assert.match(statementPdf, /sales_order_items/)
  assert.match(statementPdf, /sales_clients/)
  assert.match(statementPdf, /company_profile/)
  assert.match(statementPdf, /buildSalesStatementPdf/)
  assert.match(statementPdf, /application\/pdf/)
})

test('answer document save is a document, not a report, and preserves markdown tables', () => {
  assert.match(docxDocument, /MONI 답변 문서/)
  assert.match(docxDocument, /MONI_Answer_/)
  assert.match(docxDocument, /TableCell/)
  assert.match(docxDocument, /TableRow/)
  assert.match(docxDocument, /WidthType\.PERCENTAGE/)
  assert.match(docxDocument, /size: '100%'/)
  assert.match(docxDocument, /shading:/)
  assert.doesNotMatch(docxDocument, /MONI AI 업무 보고서/)
  assert.doesNotMatch(docxDocument, /cells\.join\('  ·  '\)/)
})

test('official business reads never mix default tenant rows into canonical MONI answers', () => {
  assert.match(toolBackend, /return \[context\.businessId\]/)
  assert.doesNotMatch(toolBackend, /\[context\.businessId, 'default'/)
})

test('current-month production comparisons use equal elapsed periods and flag implausible plan scale', () => {
  assert.match(conversationTools, /sameElapsedProductionComparison/)
  assert.match(conversationTools, /same_elapsed_day_comparison/)
  assert.match(conversationTools, /동일 경과기간 생산실적 비교/)
  assert.match(conversationTools, /suspected_scale_mismatch/)
  assert.match(conversationTools, /월간 생산계획 합계가 작업지시 규모와 비정상적으로 크게 벌어져 있습니다/)
  assert.match(conversationTools, /same_elapsed_day_comparison을 우선 사용/)
})
