import { NextRequest, NextResponse } from 'next/server'
import { getSessionFromRequest } from '@/lib/allowance/session'
import { createMoniServiceRoleClient } from '@/lib/moni/db'

export const runtime='nodejs'
export const dynamic='force-dynamic'
const BUSINESS_ID=String(process.env.MONI_BUSINESS_ID||'20220523011').trim()
const PACKAGING_BUSINESS_ID='default'
const ACTION_DOMAIN='packaging_transaction'
const txt=(v:unknown,n=1000)=>String(v??'').trim().slice(0,n)
const norm=(v:unknown)=>txt(v).normalize('NFKC').toLowerCase().replace(/[\s\-_()[\]{}.,/\\]+/g,'')
const validDate=(v:unknown)=>/^\d{4}-\d{2}-\d{2}$/.test(txt(v,10))?txt(v,10):''
const uuid=(v:unknown)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(txt(v,80))
function today(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const x=Object.fromEntries(p.map(i=>[i.type,i.value]));return `${x.year}-${x.month}-${x.day}`}
function dateHint(s:string){const m=s.match(/\b(20\d{2})[-./](\d{1,2})[-./](\d{1,2})\b/);if(m)return `${m[1]}-${String(+m[2]).padStart(2,'0')}-${String(+m[3]).padStart(2,'0')}`;if(/오늘|금일/.test(s))return today();return ''}
async function auth(req:NextRequest){const s=await getSessionFromRequest(req);if(!s)return {s:null,r:NextResponse.json({ok:false,error:'인증이 필요합니다.'},{status:401})};if(s.role!=='admin')return {s:null,r:NextResponse.json({ok:false,error:'관리자만 업무값을 변경할 수 있습니다.'},{status:403})};return {s,r:null}}
async function exchange(db:ReturnType<typeof createMoniServiceRoleClient>,thread:string){const {data,error}=await db.from('moni_ai_messages').select('id,role,content,created_at').eq('business_id',BUSINESS_ID).eq('thread_id',thread).order('created_at',{ascending:false}).limit(14);if(error)throw new Error(error.message);const rows=[...(data||[])].reverse();let i=-1;for(let n=rows.length-1;n>=0;n--)if(rows[n]?.role==='user'){i=n;break}if(i<0)return {u:null,a:null,ctx:''};return {u:rows[i],a:rows.slice(i+1).find(x=>x.role==='assistant')||null,ctx:rows.slice(Math.max(0,i-5)).map(x=>txt(x.content,2500)).join(' ')}}
function classify(current:string,ctx:string){const c=current.replace(/\s+/g,' ');const packaging=/(부재료|포장재|포장 자재|라벨|파우치|박스|봉투|리본)/.test(c)||/(부재료|포장재).*(입고|매입|수불)/.test(ctx);if(!packaging)return null;if(/삭제|지워|제거|없애/.test(c))return 'DELETE' as const;if(/수정|변경|정정|고쳐|바꿔/.test(c))return 'UPDATE' as const;if(/입고|매입/.test(c))return 'CREATE' as const;return null}
async function materials(db:ReturnType<typeof createMoniServiceRoleClient>){const {data,error}=await db.from('packaging_materials').select('id,material_name,material_code,spec,material_type,supplier,unit_price,current_stock,is_active,ingredient_type').eq('business_id',PACKAGING_BUSINESS_ID).eq('is_active',true).order('material_name');if(error)throw new Error(error.message);return data||[]}
function matchMaterial(rows:any[],s:string){const n=norm(s);return rows.map(r=>({r,n: norm(r.material_name),c:norm(r.material_code||r.id)})).filter(x=>x.n.length>=2&&(n.includes(x.n)||(x.c&&n.includes(x.c)))).sort((a,b)=>b.n.length-a.n.length)[0]?.r||null}
async function confirmation(db:ReturnType<typeof createMoniServiceRoleClient>,loginId:string,thread:string,msg:string){const {data}=await db.from('moni_action_confirmations').select('*').eq('business_id',BUSINESS_ID).eq('action_domain',ACTION_DOMAIN).eq('requested_by_login_id',loginId).eq('source_client_id',`moni-web:${thread}`).order('created_at',{ascending:false}).limit(15);return (data||[]).find((r:any)=>txt(r?.payload?.source_user_message_id,80)===msg)||null}

export async function GET(req:NextRequest){const au=await auth(req);if(au.r||!au.s)return au.r!;const thread=txt(req.nextUrl.searchParams.get('thread_id'),80);if(!uuid(thread))return NextResponse.json({ok:false,error:'유효한 thread_id가 필요합니다.'},{status:400});try{const db=createMoniServiceRoleClient(),{u,a,ctx}=await exchange(db,thread);if(!u)return NextResponse.json({ok:true,card:null});const existing=await confirmation(db,au.s.loginId,thread,String(u.id));if(existing){if(existing.status==='PENDING')return NextResponse.json({ok:true,card:{stage:'confirmation',operation:existing.action_type,source_user_message_id:u.id,confirmation_id:existing.id,preview_text:existing.preview_text,warnings:existing.warnings||[],expires_at:existing.expires_at}},{headers:{'Cache-Control':'no-store'}});if(existing.status==='EXECUTED')return NextResponse.json({ok:true,card:{stage:'completed',operation:existing.action_type,source_user_message_id:u.id,confirmation_id:existing.id,preview_text:existing.preview_text,result:existing.result_snapshot}},{headers:{'Cache-Control':'no-store'}});if(existing.status==='FAILED')return NextResponse.json({ok:true,card:{stage:'failed',operation:existing.action_type,source_user_message_id:u.id,error:existing.error_message}},{headers:{'Cache-Control':'no-store'}})}
 const op=classify(txt(u.content,5000),ctx);if(!op)return NextResponse.json({ok:true,card:null},{headers:{'Cache-Control':'no-store'}});const ms=await materials(db),combined=[txt(u.content,5000),txt(a?.content,5000),ctx].join(' '),matched=matchMaterial(ms,combined);let candidates:any[]=[];if(op!=='CREATE'){const {data}=await db.from('packaging_transactions').select('id,material_code,txn_type,quantity,note,txn_date,supplier,source_purchase_id,created_at').eq('business_id',PACKAGING_BUSINESS_ID).eq('txn_type','INBOUND').order('txn_date',{ascending:false}).order('created_at',{ascending:false}).limit(40);candidates=(data||[]).map((r:any)=>{const m=ms.find((x:any)=>x.id===r.material_code);return {id:r.id,material_id:m?.id||'',material_name:m?.material_name||r.material_code,tx_date:r.txn_date,quantity:r.quantity,supplier:r.supplier,note:r.note,protected:Boolean(r.source_purchase_id||!m),protected_reason:r.source_purchase_id?'매입 원장 연결 기록':!m?'과거 마스터 연결 불완전 기록':null}})}
 return NextResponse.json({ok:true,card:{stage:'draft',operation:op,source_user_message_id:u.id,source_assistant_message_id:a?.id||null,fields:{material_id:matched?.id||'',material_name:matched?.material_name||'',tx_date:dateHint(txt(u.content,5000))||today(),quantity:'',supplier:txt(matched?.supplier,250),note:''},material_options:ms.map((m:any)=>({id:m.id,name:m.material_name,code:m.material_code,spec:m.spec,type:m.material_type,supplier:m.supplier,unit_price:Number(m.unit_price||0),current_stock:Number(m.current_stock||0)})),candidates,evidence_note:'부재료 마스터의 연결정보를 먼저 보여주고 이번 입고값만 수정할 수 있습니다.'}},{headers:{'Cache-Control':'no-store'}})}catch(e){return NextResponse.json({ok:false,error:e instanceof Error?e.message:'부재료 업무카드 준비 실패'},{status:500})}}

export async function POST(req:NextRequest){const au=await auth(req);if(au.r||!au.s)return au.r!;const b=await req.json().catch(()=>null) as Record<string,any>|null;if(!b)return NextResponse.json({ok:false,error:'요청 본문이 필요합니다.'},{status:400});const command=txt(b.command,20).toLowerCase(),thread=txt(b.thread_id,80);if(!uuid(thread))return NextResponse.json({ok:false,error:'유효한 thread_id가 필요합니다.'},{status:400});const db=createMoniServiceRoleClient(),sourceClient=`moni-web:${thread}`;
 if(command==='execute'){const id=txt(b.confirmation_id,80);if(!uuid(id))return NextResponse.json({ok:false,error:'유효한 confirmation_id가 필요합니다.'},{status:400});try{const {data:c,error}=await db.from('moni_action_confirmations').select('id,action_domain,status,requested_by_login_id,source_client_id,expires_at').eq('id',id).eq('business_id',BUSINESS_ID).maybeSingle();if(error)throw new Error(error.message);if(!c||c.action_domain!==ACTION_DOMAIN)throw new Error('부재료 승인 건을 찾을 수 없습니다.');if(c.requested_by_login_id!==au.s.loginId||c.source_client_id!==sourceClient)throw new Error('승인 요청 주체가 일치하지 않습니다.');if(c.status!=='PENDING')throw new Error('이미 처리됐거나 실행할 수 없는 승인 건입니다.');const {data,error:rpc}=await db.rpc('moni_execute_packaging_transaction_action',{p_confirmation_id:id,p_user_confirmation_text:'모바일 업무 카드에서 확정 실행',p_actor_login_id:au.s.loginId,p_source_client_id:sourceClient});if(rpc){await db.from('moni_action_confirmations').update({status:'FAILED',error_message:txt(rpc.message,1800)}).eq('id',id).eq('status','PENDING');throw new Error(rpc.message)}return NextResponse.json({ok:true,result:data},{headers:{'Cache-Control':'no-store'}})}catch(e){return NextResponse.json({ok:false,error:e instanceof Error?e.message:'부재료 실행 실패'},{status:400})}}
 if(command!=='prepare')return NextResponse.json({ok:false,error:'지원하지 않는 카드 명령입니다.'},{status:400});const op=txt(b.operation,20).toUpperCase();if(!['CREATE','UPDATE','DELETE'].includes(op))return NextResponse.json({ok:false,error:'지원하지 않는 작업입니다.'},{status:400});const source=txt(b.source_user_message_id,80);if(!uuid(source))return NextResponse.json({ok:false,error:'원본 사용자 메시지를 확인할 수 없습니다.'},{status:400});try{const {data:msg}=await db.from('moni_ai_messages').select('id').eq('id',source).eq('thread_id',thread).eq('business_id',BUSINESS_ID).eq('role','user').maybeSingle();if(!msg)throw new Error('현재 대화의 원본 요청을 확인할 수 없습니다.');const f=b.fields&&typeof b.fields==='object'?b.fields:{};let payload:any={source_user_message_id:source,packaging_business_id:PACKAGING_BUSINESS_ID},before:any=null,preview='';const warnings:string[]=[];
 if(op==='CREATE'){const mid=txt(f.material_id,180),qty=Number(f.quantity),date=validDate(f.tx_date)||today();if(!mid)throw new Error('부재료를 선택해 주세요.');if(!Number.isInteger(qty)||qty<=0)throw new Error('입고수량은 EA 기준 양의 정수로 입력해 주세요.');const {data:m}=await db.from('packaging_materials').select('*').eq('id',mid).eq('business_id',PACKAGING_BUSINESS_ID).eq('is_active',true).maybeSingle();if(!m)throw new Error('활성 부재료 마스터에서 선택한 항목을 찾을 수 없습니다.');payload={...payload,material_id:m.id,material_name:m.material_name,quantity:qty,tx_date:date,supplier:txt(f.supplier,300)||null,note:txt(f.note,1200)||null};before={material_id:m.id,material_name:m.material_name,current_stock:Number(m.current_stock||0)};preview=`[부재료 입고 등록] ${date} · ${m.material_name} · ${qty.toLocaleString('ko-KR')} EA · 매입처 ${txt(f.supplier,300)||'미입력'} · 재고 ${Number(m.current_stock||0).toLocaleString('ko-KR')} → ${(Number(m.current_stock||0)+qty).toLocaleString('ko-KR')} EA`}
 else {const tid=txt(b.transaction_id||f.transaction_id,200);if(!tid)throw new Error(`${op==='DELETE'?'삭제':'수정'}할 부재료 입고 기록을 선택해 주세요.`);const {data:tx}=await db.from('packaging_transactions').select('*').eq('id',tid).eq('business_id',PACKAGING_BUSINESS_ID).maybeSingle();if(!tx)throw new Error('선택한 부재료 입고 기록을 찾을 수 없습니다.');if(String(tx.txn_type).toUpperCase()!=='INBOUND')throw new Error('입고 기록만 수정·삭제할 수 있습니다.');if(tx.source_purchase_id)throw new Error('매입 원장과 연결된 기록은 원본 업무에서 수정해야 합니다.');const {data:m}=await db.from('packaging_materials').select('*').eq('id',tx.material_code).eq('business_id',PACKAGING_BUSINESS_ID).maybeSingle();if(!m)throw new Error('이 과거 기록은 부재료 마스터 연결이 불완전해 직접 수정·삭제할 수 없습니다.');before={transaction:tx,material:m};if(op==='DELETE'){if(Number(m.current_stock||0)-Number(tx.quantity||0)<0)throw new Error('삭제 후 현재재고가 음수가 됩니다.');payload={...payload,transaction_id:tx.id,material_id:m.id};preview=`[부재료 입고 삭제] ${tx.txn_date} · ${m.material_name} · ${Number(tx.quantity||0).toLocaleString('ko-KR')} EA · 삭제 후 재고 ${(Number(m.current_stock||0)-Number(tx.quantity||0)).toLocaleString('ko-KR')} EA`}else{const qty=Number(f.quantity),date=validDate(f.tx_date)||tx.txn_date;if(!Number.isInteger(qty)||qty<=0)throw new Error('수정할 입고수량은 EA 기준 양의 정수여야 합니다.');if(Number(m.current_stock||0)-Number(tx.quantity||0)+qty<0)throw new Error('수정 후 현재재고가 음수가 됩니다.');payload={...payload,transaction_id:tx.id,material_id:m.id,material_name:m.material_name,quantity:qty,tx_date:date,supplier:txt(f.supplier,300)||null,note:txt(f.note,1200)||null};preview=`[부재료 입고 수정] ${tx.txn_date} · ${m.material_name} · ${Number(tx.quantity||0).toLocaleString('ko-KR')} → ${date} · ${qty.toLocaleString('ko-KR')} EA · 수정 후 재고 ${(Number(m.current_stock||0)-Number(tx.quantity||0)+qty).toLocaleString('ko-KR')} EA`}}
 }
 const {data:pending}=await db.from('moni_action_confirmations').select('id,payload').eq('business_id',BUSINESS_ID).eq('action_domain',ACTION_DOMAIN).eq('requested_by_login_id',au.s.loginId).eq('source_client_id',sourceClient).eq('status','PENDING').limit(20);const old=(pending||[]).filter((r:any)=>txt(r?.payload?.source_user_message_id,80)===source).map((r:any)=>r.id);if(old.length)await db.from('moni_action_confirmations').update({status:'CANCELLED'}).in('id',old).eq('status','PENDING');const expires=new Date(Date.now()+15*60*1000).toISOString();const {data:c,error}=await db.from('moni_action_confirmations').insert({business_id:BUSINESS_ID,action_domain:ACTION_DOMAIN,action_type:op,payload,before_snapshot:before,preview_text:preview,warnings,status:'PENDING',requested_by_login_id:au.s.loginId,requested_by_role:au.s.role,source_client_id:sourceClient,expires_at:expires}).select('id,action_type,status,preview_text,warnings,expires_at').single();if(error)throw new Error(error.message);return NextResponse.json({ok:true,confirmation:c},{headers:{'Cache-Control':'no-store'}})}catch(e){return NextResponse.json({ok:false,error:e instanceof Error?e.message:'입력값 확인 실패'},{status:400})}}
