'use client'

import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react'

type Opportunity = { id:string; title:string; stage:string; expected_amount:number; won_amount:number; close_date?:string|null; assigned_person_id?:string|null; next_action_date?:string|null }
type Person = { id:string; name:string; status:string; target:{id:string;target_amount:number;note?:string|null}|null; actual_sales_amount:number; open_pipeline_amount:number; gap_amount:number|null; attainment_rate:number|null }
type Payload = {
  ok:boolean; error?:string; range:{month:string;start:string;end:string};
  basis:{target_and_actual:string;pipeline:string};
  company:{target:{id:string;target_amount:number;note?:string|null}|null;actual_sales_amount:number;gap_amount:number|null;attainment_rate:number|null;open_pipeline_amount:number;open_pipeline_count:number;won_pipeline_amount:number;won_pipeline_count:number;no_close_date_pipeline_amount:number;no_close_date_pipeline_count:number};
  people:Person[];
  opportunities:{open_month:Opportunity[];won_month:Opportunity[];open_without_close_date:Opportunity[]};
}

const inputClass='w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500'
const secondaryButton='rounded-xl border border-slate-700 px-4 py-2.5 text-sm font-semibold text-slate-200 hover:border-slate-500 disabled:opacity-40'
const primaryButton='rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-black text-white hover:bg-blue-500 disabled:opacity-40'
function monthNow(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit'}).format(new Date()).slice(0,7)}
function money(value:unknown){return `${new Intl.NumberFormat('ko-KR',{maximumFractionDigits:0}).format(Math.round(Number(value??0)))}원`}
function pct(value:number|null){return value===null?'설정 필요':`${value.toFixed(1)}%`}
function stageLabel(stage:string){return stage==='lead'?'리드':stage==='contacted'?'접촉':stage==='proposal'?'제안':stage==='negotiation'?'협상':stage==='won'?'수주':stage==='lost'?'실패':stage}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block text-sm text-slate-300"><span className="mb-1.5 block">{label}</span>{children}</label>}
function Summary({label,value,note,tone='default'}:{label:string;value:string;note?:string;tone?:'default'|'success'|'warning'|'danger'|'pending'}){const cls=tone==='success'?'border-emerald-500/30 bg-emerald-500/[0.06] text-emerald-100':tone==='warning'?'border-amber-500/30 bg-amber-500/[0.06] text-amber-100':tone==='danger'?'border-red-500/30 bg-red-500/[0.06] text-red-100':tone==='pending'?'border-violet-500/30 bg-violet-500/[0.06] text-violet-100':'border-slate-700 bg-slate-900/60 text-white';return <div className={`rounded-2xl border p-5 ${cls}`}><div className="text-xs font-black uppercase tracking-[0.12em] opacity-60">{label}</div><div className="mt-2 text-2xl font-black">{value}</div>{note&&<div className="mt-1 text-xs leading-5 opacity-65">{note}</div>}</div>}

export default function SalesTargetsModule(){
  const [month,setMonth]=useState(monthNow())
  const [data,setData]=useState<Payload|null>(null)
  const [loading,setLoading]=useState(true)
  const [saving,setSaving]=useState(false)
  const [error,setError]=useState('')
  const [notice,setNotice]=useState('')
  const [companyTarget,setCompanyTarget]=useState('')
  const [companyNote,setCompanyNote]=useState('')
  const [personDrafts,setPersonDrafts]=useState<Record<string,string>>({})

  const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch(`/api/moni/sales-targets?month=${encodeURIComponent(month)}&_=${Date.now()}`,{cache:'no-store'});const payload=await response.json() as Payload;if(!response.ok||!payload.ok)throw new Error(payload.error||'영업 목표 데이터를 불러오지 못했습니다.');setData(payload);setCompanyTarget(payload.company.target?String(payload.company.target.target_amount):'');setCompanyNote(payload.company.target?.note??'');const drafts:Record<string,string>={};payload.people.forEach((person)=>{drafts[person.id]=person.target?String(person.target.target_amount):''});setPersonDrafts(drafts)}catch(e){setError(e instanceof Error?e.message:'영업 목표 데이터를 불러오지 못했습니다.')}finally{setLoading(false)}},[month])
  useEffect(()=>{void load()},[load])

  async function post(action:string,bodyData:Record<string,unknown>){const response=await fetch('/api/moni/sales-targets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data:bodyData})});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'저장에 실패했습니다.');return result}
  async function saveCompany(){if(companyTarget.trim()===''){setError('회사 월 목표매출을 입력해 주세요.');return}setSaving(true);setError('');setNotice('');try{await post('save_target',{month,scope_type:'company',target_amount:Number(companyTarget),note:companyNote});setNotice('회사 월 목표매출을 저장했습니다.');await load()}catch(e){setError(e instanceof Error?e.message:'목표 저장에 실패했습니다.')}finally{setSaving(false)}}
  async function clearCompany(){setSaving(true);setError('');setNotice('');try{await post('clear_target',{month,scope_type:'company'});setNotice('회사 월 목표매출 설정을 해제했습니다.');await load()}catch(e){setError(e instanceof Error?e.message:'목표 해제에 실패했습니다.')}finally{setSaving(false)}}
  async function savePerson(person:Person){const raw=personDrafts[person.id]??'';setSaving(true);setError('');setNotice('');try{if(raw.trim()==='')await post('clear_target',{month,scope_type:'person',person_id:person.id});else await post('save_target',{month,scope_type:'person',person_id:person.id,target_amount:Number(raw)});setNotice(`${person.name} 월 목표를 저장했습니다.`);await load()}catch(e){setError(e instanceof Error?e.message:'담당자 목표 저장에 실패했습니다.')}finally{setSaving(false)}}

  const company=data?.company
  const pipelineRows=useMemo(()=>[...(data?.opportunities.open_month??[]),...(data?.opportunities.won_month??[])].sort((a,b)=>String(a.close_date??'9999').localeCompare(String(b.close_date??'9999'))),[data])
  if(loading)return <main className="min-h-screen bg-[#071426] px-5 py-8 text-slate-100"><div className="mx-auto max-w-[1500px] rounded-3xl border border-slate-700 bg-[#0b1b30] p-16 text-center text-slate-400">영업 목표 데이터를 불러오는 중입니다.</div></main>

  return <main className="min-h-screen bg-[#071426] px-4 py-6 text-slate-100 md:px-8"><div className="mx-auto max-w-[1500px] space-y-5">
    <header className="rounded-3xl border border-slate-700 bg-[#0b1b30] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-black text-emerald-300">MONI SALES TARGETS</p><h1 className="mt-1 text-3xl font-black">영업 목표매출</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">목표를 실제 확정 판매와 비교합니다. 파이프라인은 입력된 예상금액 그대로 보여주며 확률 가중치는 만들지 않습니다.</p></div><Field label="목표 월"><input type="month" value={month} onChange={(e)=>setMonth(e.target.value)} className={inputClass}/></Field></div></header>
    {error&&<div className="rounded-2xl border border-red-500/40 bg-red-500/10 p-4 text-sm text-red-200">{error}</div>}{notice&&<div className="rounded-2xl border border-emerald-500/40 bg-emerald-500/10 p-4 text-sm text-emerald-200">{notice}</div>}

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary label="월 목표매출" value={company?.target?money(company.target.target_amount):'설정 필요'} note={data?.basis.target_and_actual} tone={company?.target?'success':'pending'}/><Summary label="실제 확정매출" value={money(company?.actual_sales_amount)} note="판매관리 확정 판매합계" tone="success"/><Summary label="목표 부족액" value={company?.gap_amount===null?'목표 미설정':money(company?.gap_amount)} note={`달성률 ${pct(company?.attainment_rate??null)}`} tone={company?.gap_amount===null?'pending':(company?.gap_amount??0)>0?'warning':'success'}/><Summary label="이번 달 종료예정 파이프라인" value={money(company?.open_pipeline_amount)} note={`${company?.open_pipeline_count??0}건 · 확률 가중 없음`} /></div>

    <section className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]">
      <div className="rounded-3xl border border-slate-700 bg-slate-900/55 p-5"><h2 className="text-xl font-black">회사 목표 설정</h2><p className="mt-1 text-sm leading-6 text-slate-400">현재 기준은 기존 MONI 매출표시와 동일한 부가세 포함 판매합계입니다.</p><div className="mt-5 space-y-4"><Field label="월 목표매출(원)"><input type="number" min="0" value={companyTarget} onChange={(e)=>setCompanyTarget(e.target.value)} placeholder="예: 100000000" className={inputClass}/></Field><Field label="메모"><input value={companyNote} onChange={(e)=>setCompanyNote(e.target.value)} placeholder="선택" className={inputClass}/></Field><div className="flex justify-end gap-2"><button type="button" disabled={saving||!company?.target} onClick={()=>void clearCompany()} className={secondaryButton}>목표 해제</button><button type="button" disabled={saving} onClick={()=>void saveCompany()} className={primaryButton}>저장</button></div></div><div className="mt-5 rounded-2xl border border-slate-700 bg-slate-950/30 p-4 text-xs leading-5 text-slate-500"><b className="text-slate-300">계산하지 않는 것:</b> 리드 10%, 제안 50%, 협상 80% 같은 임의 확률. 현재 CRM에는 확률 필드가 없으므로 원금액만 참고지표로 사용합니다.</div></div>
      <div className="rounded-3xl border border-slate-700 bg-slate-900/55 p-5"><div className="grid gap-3 sm:grid-cols-3"><Summary label="수주 처리 파이프라인" value={money(company?.won_pipeline_amount)} note={`${company?.won_pipeline_count??0}건 · CRM won_amount`}/><Summary label="종료일 미설정 파이프라인" value={money(company?.no_close_date_pipeline_amount)} note={`${company?.no_close_date_pipeline_count??0}건`} tone={(company?.no_close_date_pipeline_count??0)>0?'warning':'default'}/><Summary label="목표 달성률" value={pct(company?.attainment_rate??null)} note="실제 확정매출 ÷ 목표" tone={(company?.attainment_rate??0)>=100?'success':company?.target?'warning':'pending'}/></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-emerald-500 transition-all" style={{width:`${Math.max(0,Math.min(100,company?.attainment_rate??0))}%`}}/></div></div>
    </section>

    <section className="overflow-hidden rounded-3xl border border-slate-700 bg-slate-900/55"><div className="border-b border-slate-700 p-5"><h2 className="text-xl font-black">영업 담당자 목표</h2><p className="mt-1 text-sm text-slate-400">영업 프리랜서가 등록되면 개인 목표와 실제 담당 매출을 비교합니다.</p></div><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead className="bg-slate-800 text-slate-400"><tr><th className="px-4 py-3 text-left">담당자</th><th className="px-4 py-3 text-left">개인 목표</th><th className="px-4 py-3 text-left">실제매출</th><th className="px-4 py-3 text-left">달성률</th><th className="px-4 py-3 text-left">이번 달 파이프라인</th><th className="px-4 py-3 text-left">저장</th></tr></thead><tbody>{(data?.people??[]).map((person)=><tr key={person.id} className="border-t border-slate-800"><td className="px-4 py-4 font-bold">{person.name}</td><td className="px-4 py-4"><input type="number" min="0" value={personDrafts[person.id]??''} onChange={(e)=>setPersonDrafts((current)=>({...current,[person.id]:e.target.value}))} placeholder="미설정" className={`${inputClass} w-44`}/></td><td className="px-4 py-4 font-black text-emerald-200">{money(person.actual_sales_amount)}</td><td className="px-4 py-4">{pct(person.attainment_rate)}</td><td className="px-4 py-4">{money(person.open_pipeline_amount)}</td><td className="px-4 py-4"><button type="button" disabled={saving} onClick={()=>void savePerson(person)} className={secondaryButton}>저장</button></td></tr>)}{!(data?.people??[]).length&&<tr><td colSpan={6} className="px-5 py-12 text-center text-slate-500">현재 등록된 영업 프리랜서가 없습니다. 회사 목표는 위에서 바로 사용할 수 있습니다.</td></tr>}</tbody></table></div></section>

    <section className="overflow-hidden rounded-3xl border border-slate-700 bg-slate-900/55"><div className="border-b border-slate-700 p-5"><h2 className="text-xl font-black">이번 달 파이프라인 참고</h2><p className="mt-1 text-sm text-slate-400">close_date가 이번 달인 영업기회만 표시합니다. 실제매출과 합산하지 않습니다.</p></div><div className="overflow-x-auto"><table className="min-w-[850px] w-full text-sm"><thead className="bg-slate-800 text-slate-400"><tr><th className="px-4 py-3 text-left">예상종료일</th><th className="px-4 py-3 text-left">영업기회</th><th className="px-4 py-3 text-left">단계</th><th className="px-4 py-3 text-right">예상/수주금액</th></tr></thead><tbody>{pipelineRows.map((row)=><tr key={row.id} className="border-t border-slate-800"><td className="px-4 py-4 text-slate-400">{row.close_date||'-'}</td><td className="px-4 py-4 font-bold">{row.title}</td><td className="px-4 py-4">{stageLabel(row.stage)}</td><td className="px-4 py-4 text-right font-black">{money(row.stage==='won'&&row.won_amount>0?row.won_amount:row.expected_amount)}</td></tr>)}{!pipelineRows.length&&<tr><td colSpan={4} className="px-5 py-12 text-center text-slate-500">이번 달 종료예정 영업기회가 없습니다.</td></tr>}</tbody></table></div></section>
  </div></main>
}
