'use client'

/**
 * Sidebar submenu motion is intentionally disabled.
 *
 * The accordion already has its own CSS transition. A second FLIP-style
 * layout animation reacted to class changes generated by legacy hover state
 * and caused visible shaking even when the click controller immediately
 * restored the intended state.
 */
export default function SidebarSubmenuMotionController() {
  return null
}
