-- MONI security hardening batch 2.
-- Evidence before this migration:
-- - direct_public_supabase_importer_count = 0
-- - moniDb anon consumer count = 0
-- - all ordinary /api/moni routes are protected by the DB-backed MONI session boundary
-- This migration changes only RLS/grants. It does not mutate rows or business_id values.
-- ug_sales_runtime_state is intentionally excluded because it may have consumers outside this repository.

alter table public.ai_alerts enable row level security;
alter table public.business_people enable row level security;
alter table public.company_profile enable row level security;
alter table public.compliance_issues enable row level security;
alter table public.export_destinations enable row level security;
alter table public.export_document_items enable row level security;
alter table public.export_documents enable row level security;
alter table public.export_product_settings enable row level security;
alter table public.finance_accounts enable row level security;
alter table public.finance_balance_snapshots enable row level security;
alter table public.finance_settlement_payment_events enable row level security;
alter table public.finished_goods_inventory_adjustments enable row level security;
alter table public.food_type_master enable row level security;
alter table public.freelancer_settlements enable row level security;
alter table public.freelancer_work_logs enable row level security;
alter table public.mfds_products enable row level security;
alter table public.moni_ai_attachments enable row level security;
alter table public.moni_ai_messages enable row level security;
alter table public.moni_ai_project_context enable row level security;
alter table public.moni_ai_threads enable row level security;
alter table public.moni_alert_event_history enable row level security;
alter table public.moni_alert_events enable row level security;
alter table public.moni_ui_settings enable row level security;
alter table public.monthly_production_plans enable row level security;
alter table public.notification_logs enable row level security;
alter table public.official_documents enable row level security;
alter table public.product_production_units enable row level security;
alter table public.production_completion_metadata enable row level security;
alter table public.production_records enable row level security;
alter table public.products enable row level security;
alter table public.purchase_financial_reconciliation_staging enable row level security;
alter table public.purchase_payments enable row level security;
alter table public.purchase_supplier_statement_balances enable row level security;
alter table public.purchase_suppliers enable row level security;
alter table public.purchases enable row level security;
alter table public.raw_material_mapping enable row level security;
alter table public.raw_material_mapping_jb_chojang_reset_backup_20260608 enable row level security;
alter table public.raw_material_mapping_reset_backup enable row level security;
alter table public.recipe_material_mapping_history enable row level security;
alter table public.recipes enable row level security;
alter table public.sales_activities enable row level security;
alter table public.sales_client_people enable row level security;
alter table public.sales_client_product_agents enable row level security;
alter table public.sales_client_product_terms enable row level security;
alter table public.sales_client_variant_agents enable row level security;
alter table public.sales_client_variant_terms enable row level security;
alter table public.sales_clients enable row level security;
alter table public.sales_monthly_targets enable row level security;
alter table public.sales_opportunities enable row level security;
alter table public.sales_order_history enable row level security;
alter table public.sales_order_item_settlements enable row level security;
alter table public.sales_order_items enable row level security;
alter table public.sales_orders enable row level security;
alter table public.sales_price_import_audit enable row level security;
alter table public.sales_product_settings enable row level security;
alter table public.sales_product_variants enable row level security;
alter table public.sales_receipts enable row level security;
alter table public.sanitation_logs enable row level security;

revoke all on table public.ai_alerts from anon, authenticated;
revoke all on table public.business_people from anon, authenticated;
revoke all on table public.company_profile from anon, authenticated;
revoke all on table public.compliance_issues from anon, authenticated;
revoke all on table public.export_destinations from anon, authenticated;
revoke all on table public.export_document_items from anon, authenticated;
revoke all on table public.export_documents from anon, authenticated;
revoke all on table public.export_product_settings from anon, authenticated;
revoke all on table public.finance_accounts from anon, authenticated;
revoke all on table public.finance_balance_snapshots from anon, authenticated;
revoke all on table public.finance_settlement_payment_events from anon, authenticated;
revoke all on table public.finished_goods_inventory_adjustments from anon, authenticated;
revoke all on table public.food_type_master from anon, authenticated;
revoke all on table public.freelancer_settlements from anon, authenticated;
revoke all on table public.freelancer_work_logs from anon, authenticated;
revoke all on table public.mfds_products from anon, authenticated;
revoke all on table public.moni_ai_attachments from anon, authenticated;
revoke all on table public.moni_ai_messages from anon, authenticated;
revoke all on table public.moni_ai_project_context from anon, authenticated;
revoke all on table public.moni_ai_threads from anon, authenticated;
revoke all on table public.moni_alert_event_history from anon, authenticated;
revoke all on table public.moni_alert_events from anon, authenticated;
revoke all on table public.moni_ui_settings from anon, authenticated;
revoke all on table public.monthly_production_plans from anon, authenticated;
revoke all on table public.notification_logs from anon, authenticated;
revoke all on table public.official_documents from anon, authenticated;
revoke all on table public.product_production_units from anon, authenticated;
revoke all on table public.production_completion_metadata from anon, authenticated;
revoke all on table public.production_records from anon, authenticated;
revoke all on table public.products from anon, authenticated;
revoke all on table public.purchase_financial_reconciliation_staging from anon, authenticated;
revoke all on table public.purchase_payments from anon, authenticated;
revoke all on table public.purchase_supplier_statement_balances from anon, authenticated;
revoke all on table public.purchase_suppliers from anon, authenticated;
revoke all on table public.purchases from anon, authenticated;
revoke all on table public.raw_material_mapping from anon, authenticated;
revoke all on table public.raw_material_mapping_jb_chojang_reset_backup_20260608 from anon, authenticated;
revoke all on table public.raw_material_mapping_reset_backup from anon, authenticated;
revoke all on table public.recipe_material_mapping_history from anon, authenticated;
revoke all on table public.recipes from anon, authenticated;
revoke all on table public.sales_activities from anon, authenticated;
revoke all on table public.sales_client_people from anon, authenticated;
revoke all on table public.sales_client_product_agents from anon, authenticated;
revoke all on table public.sales_client_product_terms from anon, authenticated;
revoke all on table public.sales_client_variant_agents from anon, authenticated;
revoke all on table public.sales_client_variant_terms from anon, authenticated;
revoke all on table public.sales_clients from anon, authenticated;
revoke all on table public.sales_monthly_targets from anon, authenticated;
revoke all on table public.sales_opportunities from anon, authenticated;
revoke all on table public.sales_order_history from anon, authenticated;
revoke all on table public.sales_order_item_settlements from anon, authenticated;
revoke all on table public.sales_order_items from anon, authenticated;
revoke all on table public.sales_orders from anon, authenticated;
revoke all on table public.sales_price_import_audit from anon, authenticated;
revoke all on table public.sales_product_settings from anon, authenticated;
revoke all on table public.sales_product_variants from anon, authenticated;
revoke all on table public.sales_receipts from anon, authenticated;
revoke all on table public.sanitation_logs from anon, authenticated;

grant all on table public.ai_alerts to service_role;
grant all on table public.business_people to service_role;
grant all on table public.company_profile to service_role;
grant all on table public.compliance_issues to service_role;
grant all on table public.export_destinations to service_role;
grant all on table public.export_document_items to service_role;
grant all on table public.export_documents to service_role;
grant all on table public.export_product_settings to service_role;
grant all on table public.finance_accounts to service_role;
grant all on table public.finance_balance_snapshots to service_role;
grant all on table public.finance_settlement_payment_events to service_role;
grant all on table public.finished_goods_inventory_adjustments to service_role;
grant all on table public.food_type_master to service_role;
grant all on table public.freelancer_settlements to service_role;
grant all on table public.freelancer_work_logs to service_role;
grant all on table public.mfds_products to service_role;
grant all on table public.moni_ai_attachments to service_role;
grant all on table public.moni_ai_messages to service_role;
grant all on table public.moni_ai_project_context to service_role;
grant all on table public.moni_ai_threads to service_role;
grant all on table public.moni_alert_event_history to service_role;
grant all on table public.moni_alert_events to service_role;
grant all on table public.moni_ui_settings to service_role;
grant all on table public.monthly_production_plans to service_role;
grant all on table public.notification_logs to service_role;
grant all on table public.official_documents to service_role;
grant all on table public.product_production_units to service_role;
grant all on table public.production_completion_metadata to service_role;
grant all on table public.production_records to service_role;
grant all on table public.products to service_role;
grant all on table public.purchase_financial_reconciliation_staging to service_role;
grant all on table public.purchase_payments to service_role;
grant all on table public.purchase_supplier_statement_balances to service_role;
grant all on table public.purchase_suppliers to service_role;
grant all on table public.purchases to service_role;
grant all on table public.raw_material_mapping to service_role;
grant all on table public.raw_material_mapping_jb_chojang_reset_backup_20260608 to service_role;
grant all on table public.raw_material_mapping_reset_backup to service_role;
grant all on table public.recipe_material_mapping_history to service_role;
grant all on table public.recipes to service_role;
grant all on table public.sales_activities to service_role;
grant all on table public.sales_client_people to service_role;
grant all on table public.sales_client_product_agents to service_role;
grant all on table public.sales_client_product_terms to service_role;
grant all on table public.sales_client_variant_agents to service_role;
grant all on table public.sales_client_variant_terms to service_role;
grant all on table public.sales_clients to service_role;
grant all on table public.sales_monthly_targets to service_role;
grant all on table public.sales_opportunities to service_role;
grant all on table public.sales_order_history to service_role;
grant all on table public.sales_order_item_settlements to service_role;
grant all on table public.sales_order_items to service_role;
grant all on table public.sales_orders to service_role;
grant all on table public.sales_price_import_audit to service_role;
grant all on table public.sales_product_settings to service_role;
grant all on table public.sales_product_variants to service_role;
grant all on table public.sales_receipts to service_role;
grant all on table public.sanitation_logs to service_role;
